name: "Install PHAR files"

description: "Installation and verification of PHAR distributed PHP applications"

inputs:
  home:
    description: "Home path of PHIVE"
    required: false
    default: "$HOME/.phive"
  binPath:
    description: "Path of the PHIVE binary"
    required: false
    default: "${{ github.workspace }}/tools/phive"
  trustGpgKeys:
    description: "Comma separated list of trusted keys"
    required: true

runs:
  using: "composite"

  steps:
    - name: "Install PHP tools"
      shell: "bash"
      run: "'${{ inputs.binPath }}' --no-progress --home '${{ inputs.home }}' install --trust-gpg-keys ${{ inputs.trustGpgKeys }}"
