name: Tests

on: [ push, pull_request ]

jobs:

  phpcsfixer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.4"
        dependencies:
          - "highest"
    steps:
      - name: "Set default PHP version"
        run: "sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}"
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Install PHIVE"
        uses: "./.github/actions/phar-io/phive/install-phive"
      - name: "Install PHP tools"
        uses: "./.github/actions/phar-io/phive/install"
        with:
          trustGpgKeys: "4AA394086372C20A,CF1A108D0E7AE720,E82B2FB314E9906E"
      - name: "Check CS"
        run: "composer run-script tools:php-cs-fixer"

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "7.3"
          - "7.2"
        dependencies:
          - "highest"
          - "lowest"
    steps:
      - name: "Set default PHP version"
        run: "sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}"
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Install PHIVE"
        uses: "./.github/actions/phar-io/phive/install-phive"
      - name: "Install PHP tools"
        uses: "./.github/actions/phar-io/phive/install"
        with:
          trustGpgKeys: "4AA394086372C20A,CF1A108D0E7AE720,E82B2FB314E9906E"
      - name: "Determine Composer cache directory"
        uses: "./.github/actions/composer/composer/determine-cache-directory"
      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.1.1"
        with:
          path: "${{ env.COMPOSER_CACHE_DIR }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.json') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"
      - name: "Install ${{ matrix.dependencies }} dependencies with Composer"
        uses: "./.github/actions/composer/composer/install"
        with:
          dependencies: "${{ matrix.dependencies }}"
      - name: "Run unit tests"
        run: "composer run-script tools:phpunit"

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.2"
        dependencies:
          - "highest"
    steps:
      - name: "Set default PHP version"
        run: "sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}"
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Install PHIVE"
        uses: "./.github/actions/phar-io/phive/install-phive"
      - name: "Install PHP tools"
        uses: "./.github/actions/phar-io/phive/install"
        with:
          trustGpgKeys: "4AA394086372C20A,CF1A108D0E7AE720,E82B2FB314E9906E"
      - name: "Determine Composer cache directory"
        uses: "./.github/actions/composer/composer/determine-cache-directory"
      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.1.1"
        with:
          path: "${{ env.COMPOSER_CACHE_DIR }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.json') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"
      - name: "Install ${{ matrix.dependencies }} dependencies with Composer"
        uses: "./.github/actions/composer/composer/install"
        with:
          dependencies: "${{ matrix.dependencies }}"
      - name: "Run static analysis"
        run: "composer run-script tools:phpstan"
