name: Tests

on: [ push, pull_request ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: "which -a php"
      - run: "php -v"
      - run: "ls -l /usr/bin/php* || true"
      - run: "which -a composer"
      - run: "composer --version"
      - run: "echo $HOME"
      - run: "ls -ls $HOME"
      - run: "echo $PATH"

